In [1]:
#Import The require libraries

In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('loan_prediction.csv')

In [4]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [5]:
df.shape

(614, 13)

In [6]:
df.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [7]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [9]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [11]:
# drop the unwanted columns
df.drop(columns=['Loan_ID','Gender','Dependents','Self_Employed'],inplace=True)

In [12]:
df.head()

Married     Education  ApplicantIncome  CoapplicantIncome  LoanAmount  \
0      No      Graduate             5849                0.0         NaN   
1     Yes      Graduate             4583             1508.0       128.0   
2     Yes      Graduate             3000                0.0        66.0   
3     Yes  Not Graduate             2583             2358.0       120.0   
4      No      Graduate             6000                0.0       141.0   

   Loan_Amount_Term  Credit_History Property_Area Loan_Status  
0             360.0             1.0         Urban           Y  
1             360.0             1.0         Rural           N  
2             360.0             1.0         Urban           Y  
3             360.0             1.0         Urban           Y  
4             360.0             1.0         Urban           Y

In [14]:
#Handling Null Values
df['Married'].fillna('Yes',inplace=True)
df['LoanAmount'].fillna(df['LoanAmount'].mean(),inplace=True)
df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].mean(),inplace=True)
df['Credit_History'].fillna(df['Credit_History'].mean(),inplace=True)

In [15]:
df.isnull().sum()

Married              0
Education            0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [16]:
df.head()

Married     Education  ApplicantIncome  CoapplicantIncome  LoanAmount  \
0      No      Graduate             5849                0.0  146.412162   
1     Yes      Graduate             4583             1508.0  128.000000   
2     Yes      Graduate             3000                0.0   66.000000   
3     Yes  Not Graduate             2583             2358.0  120.000000   
4      No      Graduate             6000                0.0  141.000000   

   Loan_Amount_Term  Credit_History Property_Area Loan_Status  
0             360.0             1.0         Urban           Y  
1             360.0             1.0         Rural           N  
2             360.0             1.0         Urban           Y  
3             360.0             1.0         Urban           Y  
4             360.0             1.0         Urban           Y

In [17]:
x=df.drop('Loan_Status',axis=1)
y=df['Loan_Status']

In [18]:
x.shape

(614, 8)

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [20]:
ct=ColumnTransformer([('oh',OneHotEncoder(),[0,1,7])],remainder='passthrough')

In [21]:
x=ct.fit_transform(x)

In [22]:
x.shape

(614, 12)

In [23]:
x

array([[  1.        ,   0.        ,   1.        , ..., 146.41216216,
        360.        ,   1.        ],
       [  0.        ,   1.        ,   1.        , ..., 128.        ,
        360.        ,   1.        ],
       [  0.        ,   1.        ,   1.        , ...,  66.        ,
        360.        ,   1.        ],
       ...,
       [  0.        ,   1.        ,   1.        , ..., 253.        ,
        360.        ,   1.        ],
       [  0.        ,   1.        ,   1.        , ..., 187.        ,
        360.        ,   1.        ],
       [  1.        ,   0.        ,   1.        , ..., 133.        ,
        360.        ,   0.        ]])

In [24]:
from sklearn.preprocessing import LabelEncoder

In [26]:
le=LabelEncoder()

In [28]:
y=le.fit_transform(y)

In [29]:
y

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,

In [30]:
from sklearn.preprocessing import StandardScaler


In [31]:
sc=StandardScaler()

In [32]:
x=sc.fit_transform(x)

In [33]:
x

array([[ 1.37208932e+00, -1.37208932e+00,  5.28362249e-01, ...,
         3.38478577e-16,  2.79850543e-01,  4.51640451e-01],
       [-7.28815525e-01,  7.28815525e-01,  5.28362249e-01, ...,
        -2.19273315e-01,  2.79850543e-01,  4.51640451e-01],
       [-7.28815525e-01,  7.28815525e-01,  5.28362249e-01, ...,
        -9.57640999e-01,  2.79850543e-01,  4.51640451e-01],
       ...,
       [-7.28815525e-01,  7.28815525e-01,  5.28362249e-01, ...,
         1.26937121e+00,  2.79850543e-01,  4.51640451e-01],
       [-7.28815525e-01,  7.28815525e-01,  5.28362249e-01, ...,
         4.83366900e-01,  2.79850543e-01,  4.51640451e-01],
       [ 1.37208932e+00, -1.37208932e+00,  5.28362249e-01, ...,
        -1.59727534e-01,  2.79850543e-01, -2.41044061e+00]])

In [36]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [37]:
from sklearn.tree import DecisionTreeClassifier

In [38]:
df=DecisionTreeClassifier(criterion='entropy',random_state=0)

In [39]:
df.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [40]:
pred=df.predict(x_test)

In [41]:
pred

array([0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1])

In [42]:
y_test

array([1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1])

In [44]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [45]:
accuracy_score(y_test,pred)

0.7073170731707317

In [46]:
confusion_matrix(y_test,pred)

array([[20, 13],
       [23, 67]], dtype=int64)

In [47]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.47      0.61      0.53        33
           1       0.84      0.74      0.79        90

    accuracy                           0.71       123
   macro avg       0.65      0.68      0.66       123
weighted avg       0.74      0.71      0.72       123

